services:
  mysql:
    image: mysql:8.3.0
    container_name: coinbox-mysql
    environment:
      MYSQL_DATABASE: coinbox
      MYSQL_USER: coinbox
      MYSQL_PASSWORD: coinbox
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: