services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: coinbox
      MYSQL_USER: coinbox
      MYSQL_PASSWORD: coinbox
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          mysql --protocol=TCP -h 127.0.0.1
          -ucoinbox -pcoinbox
          -D coinbox -e 'SELECT 1' >/dev/null 2>&1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  mysql-data:
