spring:
  application:
    name: coinbox
  datasource:
    url: jdbc:mysql://localhost:3306/coinbox?rewriteBatchedStatements=true&useAffectedRows=true
    username: coinbox
    password: coinbox
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
  sql:
    init:
      mode: always

coinbox:
  snowflake:
    node-id: 0

springdoc:
  paths-to-match: /api/v1/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    document-title: CoinBox API
