spring:
  application:
    name: coinbox
  datasource:
    url: jdbc:mysql://localhost:3306/coinbox?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: coinbox
    password: coinbox
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100

coinbox:
  snowflake:
    node-id: ${COINBOX_SNOWFLAKE_NODE_ID:0}
